[application]
android_main_activity = "MainActivity.kt"

[bundle]
publisher = "DioxusLabs"
identifier = "com.dioxuslabs.blitz"
icon = ["./assets/blitz-logo.png"]

[bundle.windows]
webview_install_mode = "Skip"
icon_path = "./assets/blitz-logo.ico"