[package]
name = "anyrender_vello_cpu"
description = "vello_cpu backend for anyrender"
version = "0.2.0"
homepage = "https://github.com/dioxuslabs/blitz"
repository = "https://github.com/dioxuslabs/blitz"
documentation = "https://docs.rs/anyrender_vello_cpu"
license.workspace = true
edition = "2024"

[features]
default = ["vendored", "std"]
vendored = ["dep:bytemuck", "dep:skrifa", "dep:smallvec", "peniko/bytemuck"]
external = ["dep:vello_cpu"]
png = ["dep:png"]
simd = []
std = []

[dependencies]
anyrender = { workspace = true }
kurbo = { workspace = true }
peniko = { workspace = true }
softbuffer = { workspace = true }

# External vello_cpu
vello_cpu = { workspace = true, optional = true }

# Vendored vello_cpu
bytemuck = { workspace = true, features = [], optional = true }
skrifa = { workspace = true, optional = true }
smallvec = { workspace = true, optional = true }
png = { workspace = true, optional = true }
