[build]
 # additional commands to run prior to building the package
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH", 
  "apt-get update && apt-get --assume-yes install python3:$CROSS_DEB_ARCH"
]