# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "wgpu_texture"
version = "0.0.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
anyrender = { path = "../../packages/anyrender" }
anyrender_vello = { path = "../../packages/anyrender_vello" }
blitz-traits = { path = "../../packages/blitz-traits" }
blitz-dom = { path = "../../packages/blitz-dom" }
blitz-html = { path = "../../packages/blitz-html" }
blitz-shell = { path = "../../packages/blitz-shell" }
mini-dxn = { path = "../../packages/mini-dxn" }
wgpu_context = { path = "../../packages/wgpu_context" }
dioxus = { workspace = true }
wgpu = { workspace = true }
color = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true }
