[package]
name = "blitz-renderer-vello-cpu"
description = "Blitz renderer using vello_cpu"
version = "0.1.0-alpha.1"
homepage = "https://github.com/dioxuslabs/blitz"
repository = "https://github.com/dioxuslabs/blitz"
documentation = "https://docs.rs/blitz-renderer-vello-cpu"
license.workspace = true
edition = "2024"

[features]
default = ["tracing", "svg"]
tracing = ["dep:tracing"]
svg = ["blitz-dom/svg", "blitz-paint/svg"]

[dependencies]
# Blitz dependencies
blitz-paint = { path = "../blitz-paint" }
blitz-traits = { version = "0.1.0-alpha.1", path = "../blitz-traits" }
blitz-dom = {version = "0.1.0-alpha.1",  path = "../blitz-dom", default-features = false }
anyrender_vello_cpu = { path = "../anyrender_vello_cpu" }

# Linebender + WGPU dependencies
peniko = { workspace = true }
kurbo = { workspace = true }
vello_cpu = { workspace = true }
softbuffer = { workspace = true }

# Rendering dependencies
image = { workspace = true }

# Other dependencies
tracing = { workspace = true, optional = true }
