[package]
name = "blitz-renderer-vello"
version = "0.1.0"
license.workspace = true
edition = "2021"

[features]
default = ["tracing", "svg"]
tracing = ["dep:tracing"]
svg = ["dep:vello_svg", "blitz-dom/svg"]

[dependencies]
blitz-traits = { path = "../blitz-traits" }
blitz-dom = { path = "../blitz-dom", default-features = false }
style = { workspace = true, features = ["servo"] }
euclid = { workspace = true }
taffy = { workspace = true }
parley = { workspace = true }
tracing = { workspace = true, optional = true }
vello = { workspace = true }
vello_svg = { workspace = true, optional = true }
wgpu = { workspace = true }
raw-window-handle = { workspace = true }
image = { workspace = true }
futures-intrusive = { workspace = true }
pollster = { workspace = true }
