[package]
name = "blitz-renderer-vello"
version = "0.1.0"
edition = "2021"

[features]
default = ["tracing"]
tracing = ["dep:tracing"]

[dependencies]
blitz-dom = { path = "../blitz-dom" }
style = { workspace = true, features = ["servo"] }
taffy = { workspace = true }
parley = { workspace = true }
tracing = { workspace = true, optional = true }
vello = { workspace = true }
vello_svg = { workspace = true }
wgpu = { workspace = true }
raw-window-handle = { workspace = true }
image = { workspace = true }
futures-intrusive = { workspace = true }
