[package]
name = "blitz-html"
description = "Blitz HTML parser"
documentation = "https://docs.rs/blitz-html"
version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
tracing = ["dep:tracing", "blitz-dom/tracing"]

[dependencies]
# Blitz dependencies
blitz-dom = { workspace = true }
blitz-traits = { workspace = true }

# Servo dependencies
html5ever = { workspace = true }
xml5ever = { workspace = true }

tracing = { workspace = true, optional = true }
