[package]
name = "blitz-traits"
description = "Shared traits and types for Blitz"
documentation = "https://docs.rs/blitz-traits"
version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
http = { workspace = true }
url = { workspace = true }
bytes = { workspace = true }
keyboard-types = { workspace = true }
smol_str = { workspace = true }
bitflags = { workspace = true }
cursor-icon = { workspace = true }
serde = { workspace = true }
