[package]
name = "blitz-traits"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
http = { workspace = true }
url = { workspace = true }
bytes = { workspace = true }
keyboard-types = { workspace = true }
raw-window-handle = { workspace = true }
smol_str = { workspace = true }
color = { workspace = true }